-- Assignment 2 - Task 2: Database Build Script
-- CSE Motors Database Schema

-- Create enum type for account types
CREATE TYPE public.account_type AS ENUM (
    'Client',
    'Employee',
    'Admin'
);

-- Create classification table
CREATE TABLE IF NOT EXISTS public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_name VARCHAR(100) NOT NULL UNIQUE
);

-- Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    inv_make VARCHAR(100) NOT NULL,
    inv_model VARCHAR(100) NOT NULL,
    inv_year CHAR(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image VARCHAR(255) NOT NULL,
    inv_thumbnail VARCHAR(255) NOT NULL,
    inv_price DECIMAL(9,0) NOT NULL,
    inv_miles INTEGER NOT NULL,
    inv_color VARCHAR(50) NOT NULL,
    classification_id INTEGER NOT NULL,
    FOREIGN KEY (classification_id) REFERENCES public.classification (classification_id) ON DELETE CASCADE
);

-- Create account table
CREATE TABLE IF NOT EXISTS public.account (
    account_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_firstname VARCHAR(100) NOT NULL,
    account_lastname VARCHAR(100) NOT NULL,
    account_email VARCHAR(255) NOT NULL UNIQUE,
    account_password VARCHAR(255) NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'
);

-- Insert classifications
INSERT INTO public.classification (classification_name) VALUES
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

-- Insert inventory data
INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
) VALUES 
(
    'Chevy',
    'Camaro',
    '2018',
    'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!',
    '/images/camaro.jpg',
    '/images/camaro-tn.jpg',
    25000,
    101222,
    'Silver',
    2
),
(
    'Batmobile',
    'Custom',
    '2007',
    'Ever want to be a super hero? Now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during your daily commute.',
    '/images/batmobile.jpg',
    '/images/batmobile-tn.jpg',
    65000,
    29887,
    'Black',
    1
),
(
    'F-150',
    'Ford',
    '2012',
    'The Ford F-150 is an American icon. This truck offers best-in-class payload and towing capacity with advanced technology and comfort features.',
    '/images/f-150.jpg',
    '/images/f-150-tn.jpg',
    28000,
    78542,
    'White',
    4
);

-- Create indexes for better performance
CREATE INDEX idx_inventory_classification ON public.inventory(classification_id);
CREATE INDEX idx_account_email ON public.account(account_email);